set number
set relativenumber
set guifont=Iosevka:h16
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set ignorecase
set smartcase
set incsearch
set noesckeys
set modeline
set autochdir
set cinoptions=l1
colorscheme industry
set nobackup
set nowritebackup
set noswapfile
set laststatus=2
set statusline=%f%m%r%y\ %=%{&fileencoding}/%{&fileformat}\ Ln:%l/%L\ Col:%c\ %p%%